# Generated by Django 4.1.3 on 2022-12-15 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('address', models.CharField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'place title',
                'verbose_name_plural': 'place titles',
                'ordering': ['time_create', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Category title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Sport category',
                'verbose_name_plural': 'Sport categories',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('description', models.TextField(blank=True, verbose_name='place description')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('placetitle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='place.placetitle', verbose_name='Place title')),
            ],
            options={
                'verbose_name': 'place description',
                'verbose_name_plural': 'places descriptions',
                'ordering': ['description', 'placetitle_id'],
            },
        ),
        migrations.AddField(
            model_name='placetitle',
            name='sport_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.sportcategory'),
        ),
    ]
