# Generated by Django 4.1.3 on 2022-12-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_remove_description_id_alter_description_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
