# Generated by Django 4.1.3 on 2022-12-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_alter_address_time_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Place address', 'verbose_name_plural': 'Place addresses'},
        ),
        migrations.AlterModelOptions(
            name='description',
            options={'ordering': ['description', 'address_id'], 'verbose_name': 'Place description', 'verbose_name_plural': 'Places descriptions'},
        ),
        migrations.AlterModelOptions(
            name='sportcategory',
            options={'ordering': ['title', 'id'], 'verbose_name': 'Sport category', 'verbose_name_plural': 'Sport categories'},
        ),
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.TextField(blank=True, verbose_name='Place description'),
        ),
        migrations.AlterField(
            model_name='sportcategory',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Category title'),
        ),
    ]
